'use client';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Box, Flex, Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import "./globals.css";
import useThemeStore from "@/store/themeStore";
import Sidebar from "./components/layout/Sidebar";
import Header from "./components/layout/header";
import React,{useEffect} from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const theme = useThemeStore((state) => state.appearance);
  const setAppearance = useThemeStore((state) => state.setAppearance);
  const [loading, setLoading] = React.useState(true);

  useEffect(()=>{
    rememberDarkMode()
  },[])
  const rememberDarkMode = () => {
    const isDark = localStorage.getItem("isDark");
    if (isDark) {
      setAppearance("dark")
    }

    setLoading(false)

  }
  if(loading){
    return <Box></Box>
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Theme appearance={theme} >
          <Box>
            <Flex direction={{sm:"row", xs:"column", initial:"column"}} >
              {/* sidebar */}
              <Box width={{sm:"25%", xs:"100%"}}>
                <Sidebar />
              </Box>
              {/* main panel */}
              <Box width={{sm:"75%", xs:"100%", initial:"100%"}}>
                <Box display={{sm:"block", xs:"none",  initial:"none"}}>
                  <Header />
                </Box>

                {children}
              </Box>
            </Flex>
          </Box>
        </Theme>
      </body>
      
    </html>
  );
}
