'use client';

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Box, Flex, Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import "./globals.css";
import useThemeStore from "@/store/themeStore";
import Sidebar from "./components/layout/Sidebar";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const theme = useThemeStore((state) => state.appearance);


  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Theme appearance={theme} >
          <Box>
            <Flex direction={"column"} >
              {/* sidebar */}
              <Box style={{width:"25%"}}>
                <Sidebar />
              </Box>
              {/* main panel */}
              <Box style={{width:"75%"}}>
                
              </Box>
            </Flex>
          </Box>
          {children}
        </Theme>
      </body>
      
    </html>
  );
}
